### ISSUE TITLE
Point-dipole incident field

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adda-team/adda#149]
```
Implement incident field as a radiation of a point dipole. This is interesting 
from a fundamental viewpoint, but may also have certain practical implications 
(e.g. amplification of molecular, possibly Raman, scattering by metallic 
nanoparticles). 

For now workaround is possible by using '-beam read ...' command line option.

```

Original issue reported on code.google.com by `yurkin` on 6 Jun 2012 at 5:01
- Blocking: #168

**Comment by myurkin** [comment]
A recent paper http://dx.doi.org/10.1021/acsnano.5b04974 is the first to use this feature for particles near substrate. However, not many details are given.

**Comment by myurkin** [comment]
I have updated the manual to describe the case, when intrinsic losses are present (corresponding intrinsic quantum yield q0<1) based on Moskalensky A.E. and Yurkin M.A. Energy budget and optical theorem for scattering of source-induced fields, [_Phys. Rev. A_ **99**, 053824](http://doi.org/10.1103/PhysRevA.99.053824) (2019).

The remaining issue is accounting for absorption in the substrate - that is discussed in #133 .
