### ISSUE TITLE
The error with Parallel mode MPI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adda-team/adda#151]
```
Hello：
   When I use the Parallel mode with MPI ，I enter “mpiexec –n <N> ./adda_mpi ...“.However， the terminal show that “[proton:10319] *** End of error message ***
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 10313 on node proton exited on 
signal 6 (Aborted).
--------------------------------------------------------------------------
8 total processes killed (some possibly by mpiexec during cleanup)“
    I want to know where is the error.Thank you 

```

Original issue reported on code.google.com by `zxiaomi...@gmail.com` on 3 Jul 2012 at 12:20

**Comment by housebaby** [comment]
@GoogleCodeExporter  I encountered the same problem , have you figured it out why and how to solve it?

Redirecting stderr to file exp_cntk//log/train_cntk_TrainDNN.logrank0
Redirecting stderr to file exp_cntk//log/train_cntk_TrainDNN.logrank1
--------------------------------------------------------------------------
WARNING: A process refused to die despite all the efforts!
This process may still be running and/or consuming resources.

Host: 10
PID:  53846

--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 53845 on node 10 exited on signal 9 (Killed).
--------------------------------------------------------------------------

**Comment by myurkin** [comment]
@housebaby, Overall, that is the expected behavior of the MPI framework, when the underlying application dies due to some internal error. So one should look at the specific error output of this application. If you have a specific question about ADDA, please open a new issue.
