### ISSUE TITLE
Patch for /trunk/src/const.h

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adda-team/adda#208]
```
Coated nanorod shape.
```

Original issue reported on code.google.com by `zl...@nd.edu` on 20 May 2015 at 3:30

Attachments:
- [const.h.patch](https://storage.googleapis.com/google-code-attachments/a-dda/issue-208/comment-0/const.h.patch)

**Comment by myurkin** [comment]
Closing this issue, as no progress is visible
