### ISSUE TITLE
ADDA can be compiled the Opencl mode in Nividia graphics+ubuntu 14.04 32bit?

### ISSUE THREAD

**Issue by 905452934** [adda-team/adda#221]
NIvidia GeForce GT330+Ubuntu 14.04 32bit can comliled the opencl mode.
get the error:
'clfftVersionMajor' undeclared.

this error caused by AMD clfft not installed.

the AMD clfft can be installed on Nividia?

**Comment by mapclyps** [comment]
The clFFT library works perfectly on Nvidia cards as well.
In Ubuntu 16.04 the library is also in the repository (libclfft-dev).
For older Ubuntu version I would recommend installing the latest binaries of clFFT from 
https://github.com/clMathLibraries/clFFT/releases

However I see another problem with the GT330 in adda. 
Unfortunately from the 3xx series there were no GPUs for double precision calculations as it was an intermediate series (only OEM and mobile as far as I remember). 
As adda was built for using double precision it will not run in your configuration on the GPU.
A switch in adda for single precision mode is not implemented yet (see also #119)
