### ISSUE TITLE
clamdfft is not only supported 64 in adda 1.3?

### ISSUE THREAD

**Issue by 905452934** [adda-team/adda#222]
https://github.com/clMathLibraries/clFFT
my pc is ubuntu 14.04 32bit.
Can not compile clamdfft.
How to compile 32 on the computer ADDA in opencl mode

**Comment by myurkin** [comment]
I am not sure about 32 bit clamdfft, but you can try compile option `CLFFT_APPLE` for ADDA as a workaround. See https://github.com/adda-team/adda/blob/wiki/CompilingADDA.md#compilation-options

**Comment by 905452934** [comment]
Thanks! I have solved this problem.
the clfft2.2.0 support 32 bit.
I have compiled and run the code on ubuntu 14.04 32bit +AMD Graphics.
Thanks!
