### ISSUE TITLE
In OpenCL mode, Can I get the detailed steps on the FFT？

### ISSUE THREAD

**Issue by 905452934** [adda-team/adda#223]
adda-team:
       I can't understand the FFT on opnecl mode, Can I get the detailed steps on the FFT？
       Thanks!

**Comment by 905452934** [comment]
Merry Christmas! No body replay.

**Comment by myurkin** [comment]
Your question is very broad. So I can only give a few hints.

The overall workflow of FFT in opencl mode is not different from the standard mode. For both you can look at https://github.com/adda-team/adda/blob/wiki/CodeDesign.md#fft-routines, especially at the picture https://github.com/adda-team/adda/blob/wiki/fft.svg . Other parts of that wiki page may also contain relevant opencl functions (like `oclinit`). Mind, however, that it is a bit outdated (corresponds to version 1.2).

Apart from that there are some comments in the code itself.
