### ISSUE TITLE
Will you open the code about the radiation force calculation using FFT?

### ISSUE THREAD

**Issue by 905452934** [adda-team/adda#224]
According to the introduction of this article(Hoekstra A G, Frijlink M, Waters L, et al. Radiation forces in the discrete-dipole approximation[J]. JOSA A, 2001, 18(8): 1944-1953.). I wrote the calculation of radiation force code, using FFT. But encountered some problems, I would like to refer to your implementation.

**Comment by myurkin** [comment]
I have just added the [comment](https://github.com/adda-team/adda/issues/14#issuecomment-286627115) to #14, describing my knowledge of this issue. Basically, this code is lost in time - that is why we currently have an open issue #14. 

So if you have further comments, please add it directly to that issue.
