### ISSUE TITLE
Nearfield compile

### ISSUE THREAD

**Issue by limjoowon** [adda-team/adda#230]
I am trying to compile following the manual of nearfield on my desktop (Ubuntu).
When I type "make" to compile (which is the first step of the manual), I encounter the following error.

**_nearfield.f:28: Error: Can't open included file 'mpif.h'_**

So after that, I installed 'openmpi' and checked that 'mpif.h' is in the folder of '/Home/openmpi/include'.
(But I did not add environment variables)

What should I do next?
Could you give me some comments how I can sort it out?

Thank you in advance!

**Comment by limjoowon** [comment]
Solved by chaning as following,
MPIFC  = $(FC) -I/usr/lib/x86_64-linux-gnu/openmpi/include

This time, another error encountered,

/usr/bin/ld: cannot find -lfmpich2g

Any comment?

**Comment by myurkin** [comment]
In the [misc/near_field/Makefile](https://github.com/adda-team/adda/blob/master/misc/near_field/Makefile) try changing to `MPIFC = mpifort` and removing `MPILIBS= -lfmpich2g`. Basically, you need to remove `MPICH2` related parts and add `openmpi` ones. For the latter see https://www.open-mpi.org/faq/

**Comment by limjoowon** [comment]
Thank you for your prompt reply.
I think that it's better to stick to MPICH2 rather than openmpi.
I am not sure which version of MPICH I should install.
It should be fine if I download the latest version at "http://www.mpich.org/downloads/"?

**Comment by myurkin** [comment]
Well, I think that changing a couple of lines in the `Makefile` is easier than installing another MPI implementation. But if you want to go with `MPICH2`, the latest version should be fine, although I haven't updated my `MPICH2` for two years. 

Some relevant hints can be found in https://github.com/adda-team/adda/blob/wiki/InstallingMPI.md (with regards to ADDA itself), however, it doesn't touch upon MPI Fortran, since ADDA MPI part is purely in C.

**Comment by limjoowon** [comment]
I installed the MPICH following the manual provided (adda/InstallingMPI.md) and checked that adda_mpi works.
Back again the compile of nearfield, I attach the part of Makefile that I am using now.

# ---- GNU Fortran Compiler
FC     = gfortran
FFLAGS = -O3 -ffast-math -funroll-loops $(EXTRA_FLAGS)
#MPIFC  = $(FC)
MPIFC  = $(FC) -I/home/adminimt/mpich-3.2.1/src/include
LIBS   =
#MPILIBS= -lfmpich2g
MPILIBS= -L/home/adminimt/mpich-3.2.1/src/lib

At first, I set MPILIBS to be '-lfmpich2g' but it did not work so I changed it to 'MPILIBS= -L/home/adminimt/mpich-3.2.1/src/lib' and got the follwoing results.

------------------------------------------------------------------------------------------------------------------------------------gfortran -I/home/adminimt/mpich-3.2.1/src/include  -O3 -ffast-math -funroll-loops  -o nearfield nearfield.f -L/home/adminimt/mpich-3.2.1/src/lib xfuty.o nfsubs.o
/tmp/cctwRC8c.o: In function `computenearfield_':
nearfield.f:(.text+0x4b): undefined reference to `mpi_init_'
nearfield.f:(.text+0x7d): undefined reference to `mpi_comm_rank_'
nearfield.f:(.text+0x91): undefined reference to `mpi_comm_size_'
nearfield.f:(.text+0x107): undefined reference to `mpi_bcast_'
nearfield.f:(.text+0x131): undefined reference to `mpi_bcast_'
nearfield.f:(.text+0x15b): undefined reference to `mpi_bcast_'
nearfield.f:(.text+0x2f9): undefined reference to `mpi_bcast_'
nearfield.f:(.text+0x356): undefined reference to `mpi_bcast_'
/tmp/cctwRC8c.o:nearfield.f:(.text+0x3af): more undefined references to `mpi_bcast_' follow
/tmp/cctwRC8c.o: In function `computenearfield_':
nearfield.f:(.text+0x11b3): undefined reference to `mpi_reduce_'
nearfield.f:(.text+0x11e7): undefined reference to `mpi_reduce_'
nearfield.f:(.text+0x121f): undefined reference to `mpi_reduce_'
nearfield.f:(.text+0x1252): undefined reference to `mpi_reduce_'
nearfield.f:(.text+0x12c2): undefined reference to `mpi_finalize_'
collect2: error: ld returned 1 exit status
Makefile:56: recipe for target 'nearfield' failed
make: *** [nearfield] Error 1
------------------------------------------------------------------------------------------------------------------------------------

I think there is something wrong regarding the assignment of MPILIBS. 
Which directory should I assign to MPILIBS?

**Comment by myurkin** [comment]
You probably need both on MPILIBS, i.e.
`MPILIBS= -lfmpich2g -L/home/adminimt/mpich-3.2.1/src/lib`

But you may also solve this problem by using `mpifort`, as I mentioned above for `openmpi` (search for mpifort in MPICH docs).

**Comment by limjoowon** [comment]
Thank you for suggestion.
I tried what you said as 'MPILIBS= -L/home/adminimt/mpich-install/lib -lfmpich2g'.
What I observe is that as long as MPILIBS contains -lfmpich2g, it shows the following error,

gfortran -I/home/adminimt/mpich-install/include  -O3 -ffast-math -funroll-loops  -o nearfield nearfield.f -L/home/adminimt/mpich-install/lib -lfmpich2g xfuty.o nfsubs.o
/usr/bin/ld: cannot find -lfmpich2g

I also attach the version information of MPICH just in case it may be needed,

HYDRA build details:
    Version:                                 3.2.1
    Release Date:                            Fri Nov 10 20:21:01 CST 2017
    CC:                              gcc    
    CXX:                             g++    
    F77:                             gfortran   
    F90:                             gfortran   
    Configure options:                       '--disable-option-checking' '--prefix=/home/adminimt/mpich-install' '--cache-file=/dev/null' '--srcdir=.' 'CC=gcc' 'CFLAGS= -O2' 'LDFLAGS=' 'LIBS=-lpthread ' 'CPPFLAGS= -I/home/adminimt/mpich-3.2.1/src/mpl/include -I/home/adminimt/mpich-3.2.1/src/mpl/include -I/home/adminimt/mpich-3.2.1/src/openpa/src -I/home/adminimt/mpich-3.2.1/src/openpa/src -D_REENTRANT -I/home/adminimt/mpich-3.2.1/src/mpi/romio/include' 'MPLLIBNAME=mpl'
    Process Manager:                         pmi
    Launchers available:                     ssh rsh fork slurm ll lsf sge manual persist
    Topology libraries available:            hwloc
    Resource management kernels available:   user slurm ll lsf sge pbs cobalt
    Checkpointing libraries available:       
    Demux engines available:                 poll select

**Comment by myurkin** [comment]
That seem to be related to your particular installation, so I do not have any more advices. However, you may also try the `mpifort` approach (see above) with `MPICH` as well - see https://www.mpich.org/static/docs/v3.1.2/www1/mpifort.html

**Comment by limjoowon** [comment]
I managed to follow the first step of the manual by setting "MPILIBS= -L/home/adminimt/mpich-install/lib -lmpich -lopa -lmpl  -lrt -lpthread"

I am working on the second step

Since './runall' shows some errors, I think I have to set following variables.

export ADDABIN=youraddbinary
export MPIEXEC="MPIinvocation"

Which directories should I put for 'youraddbinary' and 'MPIlinvocation'?
Could you clarify them?

**Comment by myurkin** [comment]
Actually, in some cases the script should define those variables itself. If that does not work you may specify them explicitly. Then `ADDABIN` should be the full path to `adda` binary, and `MPIEXEC` is the command to run mpi, like `mpiexec -n 4`.

But you should really look into the error messages that you obtained.

**Comment by limjoowon** [comment]
Thank you. Solved.
