### ISSUE TITLE
Particular shape

### ISSUE THREAD

**Issue by limjoowon** [adda-team/adda#232]
Hello,

I am reading the manual, especially 6.3 Construction of a dipole set.
I would like to build a particular shape and structure of dipole sets using MATLAB and use it instead of using predefined shapes.

I think that I can do it by using '-shape read <filename>' command.
But I have no idea what kind of information the file should contain.
In the manual, it is written to refer the section of B.5 for details but where can I find the section??

Could you give me some information or comments?
(It would be very nice if I can get some example files.)

Thank you in advance!

**Comment by myurkin** [comment]
You can click on B.5 to get there. Or use the Contents in the beginning of the manual.

To get the sample files, use `ADDA` itself, and `-save_geom -prognosis`. For example,
`adda -shape sphere -save_geom -prognosis`

P.S. The discussion group is probably more suitable for such questions: https://groups.google.com/forum/#!forum/adda-discuss

**Comment by limjoowon** [comment]
Thank you!
I will use the discussion group if I have another question regarding it!
