### ISSUE TITLE
ADDA in ubuntu 16.04.4

### ISSUE THREAD

**Issue by hazraatrayee** [adda-team/adda#233]
After downloading the ZIP file and extracting it into home I found that there is no adda c program file under seq folder. 

During linking when "make seq" command is executed while positioned in src it is showing error as mentioned below.

dell@dell-OptiPlex-3050:~$ cd adda-master
dell@dell-OptiPlex-3050:~/adda-master$ cd src
dell@dell-OptiPlex-3050:~/adda-master/src$ make seq
--- Compilation options: ---
Release mode
FFTW3
Compiler set 'gnu'
----------------------------
Compiling sequential version of ADDA
make -C seq
make[1]: Entering directory '/home/dell/adda-master/src/seq'
g77 -c -O3 -ffast-math -funroll-loops -w  ../fort/d07hre.f
make[1]: g77: Command not found
../common.mk:81: recipe for target 'd07hre.o' failed
make[1]: *** [d07hre.o] Error 127
make[1]: Leaving directory '/home/dell/adda-master/src/seq'
Makefile:481: recipe for target 'seq' failed
make: *** [seq] Error 2

Could you please help me regarding his problem.

**Comment by myurkin** [comment]
Please provide the particular error message that you get during compilation. Otherwise, please read carefully https://github.com/adda-team/adda/blob/wiki/CompilingADDA.md - it may contain a solution to your problem. In particular, look at the required libraries (dependencies).

**Comment by hazraatrayee** [comment]
Dear Sir,
Thank you for your kind reply and information. I have edited the problem
and have provided the error message showing.

Regards


Atrayee Hazra

PhD Scholar

M. N. D. School of Material Science and Engineering

Indian Institute of Engineering Science and Technology, Shibpur

(Formerly known as Bengal Engineering and science University, Shibpur),

West Bengal, India.

Mobile No. 9830702646

**Comment by DaveOri** [comment]
I think you didn't installed a fortran 90 compiler the Makefile fallsback to g77 which is expected to fail.
Install gfortran
```
sudo apt install gfortran
```

**Comment by hazraatrayee** [comment]
Thank you very much for your kind reply. the problem is solved and ADDA has been installed successfully by installing gfortran.
