### ISSUE TITLE
Defining a scatterer 

### ISSUE THREAD

**Issue by hazraatrayee** [adda-team/adda#247]
I am new to ADDA. As a first step I want to run the code for a spherical nanoparticle with radius 8nm i.e. 0.008um. I have some queries regarding defing such scatterer.
1. Is this radius is r_ef i.e. effective eadius or it is x?
2. How can I define such scattere in terms of dpl, nx, Dx?
3. Other than fine tuning to get appropriate effective size what is the basic thumb rule to define a such scatterer?

I have gone through FAQ and tutorial, but it is not clear to me how the radius is 2Π by the command 
`adda –grid 16 –m 1.5 0 –size 1 –lambda 1`

Please help so that I can proceed to calculations.

**Comment by myurkin** [comment]
1. It is the effective radius r_ef, so x = k*r_ef
2. Read section 6.2 of the manual
3. For nanoparticles the safest is to manually set a grid to a rather large value, e.g.
```
adda -size 0.016 -lambda ... -grid 32 -m ... 
```

The line from tutorial that you mentioned sets the diameter (1) equals to wavelength (1). If `-lambda 1` is omitted, then wavelength would be equal to 2Π and, thus, not equal to diameter anymore.

**Comment by hazraatrayee** [comment]
Thank you very much Sir, for your kind reply.

So basically for an example if I have a particle with diameter of say 20nm, the command will be like:

`adda -size 0.02 -lambda ... -grid 32 -m ... `

And by the grid I am specifying n_x. With higher n_x the size of each dipole will decrease and it will improve the shape accuracy. Is that so?

**Comment by myurkin** [comment]
Yes, that is correct.

**Comment by hazraatrayee** [comment]
Thank you very much Sir.
