### ISSUE TITLE
gridspace for rectangular dipoles

### ISSUE THREAD

**Issue by dsmunev** [adda-team/adda#255]
'gridspace' is a legacy variable in ADDA https://github.com/adda-team/adda/blob/master/src/make_particle.c#L2218
Many places in code still use gridspace instead of gridspaceX, Y, and Z, imply that gridspace==gridspaceX, but sometimes mistake happens https://github.com/adda-team/adda/pull/245/commits/d2796c8e2a5cb1e61547340e2c1d1605d486df16

Code could become clearer, if 'gridspace' was completly removed. Maybe we can have gridspace as the maximal one (instead of maxRectScale). Or even have short variables dX, dY, dZ, and dMax. The latter is very convenient for describing the dipole size all over the code and documentation. Then we can avoid a lot of details like "along the greatest dimension".

### Related issues:
https://github.com/adda-team/adda/pull/245
https://github.com/adda-team/adda/issues/196

**Comment by myurkin** [comment]
Related modifications:
- It would be more convenient to have kdX, kdY, kdZ. 
- Default dpl is not very adequate. I would expect "adda -rect_dip 1 1 2" and "adda -rect_dip 2 2 1" to produce the same result. But now it is not. This is related to defining dMax - then dpl can be linked to it.
- Rework logic in interaction.c related to UnitsGridToCoord. To get "Coord" we need to multiply by gridSpace. This need to be fixed together with removing rectScale altogether. Related is the proper definition of ZsumShift.
