### ISSUE TITLE
New structure

### ISSUE THREAD

**Issue by hazraatrayee** [adda-team/adda#263]
I have simulated for coated structures. The domain for pre-exsisting shape if 2. I want to simulate for coated structure with two different shell and so i need to simulate for 3 domain particle. How can I generate such structure file? Please help me out.

**Comment by myurkin** [comment]
Indeed, ADDA can not construct the three-layer shape automatically. You need to provide the shape file, see https://github.com/adda-team/adda/wiki/FAQ#how-to-simulate-light-scattering-by-a-particle-which-shape-can-not-be-described-by-any-of-the-adda-predefined-shapes for possible options.
