### ISSUE TITLE
Spectrum generation

### ISSUE THREAD

**Issue by hazraatrayee** [adda-team/adda#267]
I have written some C programs and then by using shell script I am now able to generate whole spectrum of any shape just in a single run.

The spectrum that I am generating is having some problem of getting a huge extra features other than the expected one.
This problem is not there is I select a simple spherical shape. but whenever I am generating the spectrum of a core-shell structure, there are a number of extra peaks and glitches humps. This might be due to some calculation problem.

Can you please suggest me how to overcome such problems.

**Comment by myurkin** [comment]
It's hard to say for sure. But a general advice is to consider a problem for a single wavelength. Choose the one, which result you considered weird and take a look at your shape and its discretization. 

The possible problem for a core-shell structure is insufficient number of dipoles per shell thickness. The easiest test is to increase "-grid ..." and see, whether the result change and whether they converge to some value.

**Comment by hazraatrayee** [comment]
Thank Your for reply. let me first try by changing the grid value.  If the problem resolves then fine otherwise I will ask again.
