### ISSUE TITLE
Using absolute path for -init_field read can cause overflow

### ISSUE THREAD

**Issue by alkichigin** [adda-team/adda#271]
### Describe the bug
When using '-init_field read <filename>' option with absolute paths, ADDA may crash 

### To reproduce
1. run "adda -store_int_field -dir '/a/very/very/long/path/to/my/execution/directory/where/my/runs/are/stored'" 
2. run "adda -init_field read '/a/very/very/long/path/to/my/execution/directory/where/my/runs/are/stored/IntField-Y'" 
3. adda will crash while executing line "sprintf(tmp_str,"%s"RESID_STRING"\n",descr,0,prev_err);" from iterative.c

### Cause
Variable tmp_str is initialized as "char tmp_str[MAX_LINE];", where MAX_LINE is defined to be 100. 

### Possible solutions
1. Increase MAX_LINE
2. Split "sprintf(tmp_str,...)" to not include RESID_STRING etc, and printf that information separately.

**Comment by alkichigin** [comment]
3. There are no problems with using "-dir /very/long/path/..." , so I suggest using same code-ideology for "-init_field read /very/long/path/..." if that works

**Comment by myurkin** [comment]
Fixed by commit 2c0774e . Please verify.
