### ISSUE TITLE
New structure generation

### ISSUE THREAD

**Issue by hazraatrayee** [adda-team/adda#287]
Dear Maxim, I am trying to incorporate a new structure and so was following the instructions.
As my clstructire will be somewhat like coated, so I was going through it. I am unable to understand what is sh_pars[0]...sh_para[3]. From where they are getting values and what values are being assigned?
Could you please help in this matter

**Comment by myurkin** [comment]
Please take a look at https://github.com/adda-team/adda/wiki/AddingShape 

Array `sh_pars` is initialized in `param.c` from the values in the command line after '-shape <name>`

**Comment by hazraatrayee** [comment]
I have searched for a number of times but unable to find where this sh_pars[] are initialized.
After -shape <name> there are arguments. But which one is assigned to which that is not clear to me.
Please help me out

**Comment by myurkin** [comment]
https://github.com/adda-team/adda/blob/3f9b7b0fc9eddf3bbcbd1160b8e306f773787cff/src/param.c#L1502

But you do not need to worry about (or change) its initialization. Just assume that corresponding parameters of the command line are stored into this array. The order is the same as given in the command line, starting from the first value after the name of the shape (e.g., coated).

**Comment by hazraatrayee** [comment]
I am trying to generate a coated sphere that will contain a spherical particle and then two shells. 
As mentioned in make particle.c in line no 1554, coat_X and so on assigned by sh_pars[], i am a little bit confused here. What is then coat ratio
How can I introduce in the new geometry where there will be 3 different materials?

**Comment by myurkin** [comment]
https://github.com/adda-team/adda/blob/3f9b7b0fc9eddf3bbcbd1160b8e306f773787cff/src/make_particle.c#L1554

This line assigns coat_ratio (first value after `-shape coated`). But in your case you will need 2 ratios. Those variables should be defined and used in `make_particle.c`, the new shape (and corresponding values of the command line) should be described in `param.c`. Both these issues are discussed in https://github.com/adda-team/adda/wiki/AddingShape

**Comment by hazraatrayee** [comment]
So if I put 5 or 6 value after -shape <name> then all the values will be automatically be stored in sh_pars[]?

**Comment by myurkin** [comment]
Yes, exactly. But you need to specify this number of arguments in the corresponding line of constant array `shape_opt`.

**Comment by hazraatrayee** [comment]
What is Test Range II (coat_ratio, "inner/outer diameter ratio", 0,1) in case SH_COATED in make particle.c signifies?

**Comment by myurkin** [comment]
The obvious way to answer this question is to look at its definition (search over the whole code never harms). Look around the following line:
https://github.com/adda-team/adda/blob/3f9b7b0fc9eddf3bbcbd1160b8e306f773787cff/src/param.h#L70
Basically, it tests whether the value given in the command line fits certain bounds.

**Comment by hazraatrayee** [comment]
Thank you for the clarification. Actually I work in experimental area. This
is first time I am going through coding in detail. So I am facing a
little problem in understanding and sometime locating the initialization.

I really appreciate your patience and promt response.

Yours sincerely

Atrayee Hazra

**Comment by myurkin** [comment]
Sure, I am glad to help. Overall, the code has a lot of comments, but to find them you sometimes need to navigate between different source files. For that a general advice is to employ some tools that allow some search over multiple files. The most general is some IDE (integrated development environment), but even searching for text in all files in a folder using some system tools may be sufficient. You may also use the search built into GitHub, e.g., https://github.com/adda-team/adda/search?q=TestRangeII

**Comment by hazraatrayee** [comment]
Thank you for this information.
As my structure contains 3 domain, so do I need to use three sh_from_str_? As I saw that it would be replaced by box size along x axis. 
Again before shape initialization it is written that for some shapes sh_from_str2 can be left uninitialized.
So can you please help me to understand what is the function of this sh_from_str?

**Comment by myurkin** [comment]
Thanks for pointing this out. The comments have been outdated - I have fixed that. See the lines around
https://github.com/adda-team/adda/blob/db55e820b6829278ee4243ed81ceec15be2b8780/src/make_particle.c#L1818
The number of different sh_form_str# is two independently of the number of domains - it is before and after sizeX.

Hope, now it's more clear.

**Comment by hazraatrayee** [comment]
Unfortunately I am unable to understand this one. I have tried but somehow am stuck. Please could you help me

What is that before and after box size?

**Comment by myurkin** [comment]
It is two strings that appear in `log` to describe the shape. Just try something like "AAA" and "BBB" and see how it affects the output. And look how it is done for other shapes, as I mentioned before.

But, anyway, it does not affect the simulation results. So you do not need to worry about that too much.

**Comment by myurkin** [comment]
Atrayee, do you have any more questions about this issue? Or can it be considered solved?

**Comment by hazraatrayee** [comment]
Actually in previous days I was doing my experimental works. Please give me
a few more days to solve this new structure generation

Atrayee Hazra

**Comment by myurkin** [comment]
Sure, take your time.

**Comment by hazraatrayee** [comment]
[1469](https://github.com/adda-team/adda/blob/master/src/make_particle.c) `				sh_form_str1="bisphere; diameter(d):";`
I have found that almost in every shape there is a diameter mention. Which diameter is it? because we are giving the values of ratio depending on the structures. 
there is a log file for example where i have found that there is a constant value `misc/parse_log/example.nb
so do i need to give this diameter value? if yes then where? Please help me out

**Comment by hazraatrayee** [comment]
There is one shape parameter [coat_r2](https://github.com/adda-team/adda/blob/master/src/make_particle.c) `static double coat_x,coat_y,coat_z,coat_r2;` 
most of the time it has been initialized as, `coat_r2=0.25*coat_ratio*coat_ratio`  and latter it is used to identify domain.

what is the reason for this 0.25?
is that because: the particle is assumed to be within -1/2 to +1/2 and then we are just accounting one half (may be along +ve x axis) to design by knowing the domains and then by symmetry it will generate the total structure? 
this coat_r2 will determine the outer surface of the particle?

**Comment by myurkin** [comment]
> [1469](https://github.com/adda-team/adda/blob/master/src/make_particle.c) ` sh_form_str1="bisphere; diameter(d):";`
> I have found that almost in every shape there is a diameter mention. Which diameter is it? because we are giving the values of ratio depending on the structures.

This diameter is given as the argument to the `-size` command line option or calculated from other input. Importantly, it is not an integral part of the shape (which is defined by dimensionless ratios). Any shape can then be scaled using `-size`. This explains the extra complications in specifying the description strings. See Section 6.2 "The computational grid" of the manual for more details.


> There is one shape parameter [coat_r2](https://github.com/adda-team/adda/blob/master/src/make_particle.c) `static double coat_x,coat_y,coat_z,coat_r2;`
> most of the time it has been initialized as, `coat_r2=0.25*coat_ratio*coat_ratio` and latter it is used to identify domain.> 
> what is the reason for this 0.25?

Your answer is almost correct. But you should not search for a lot of sense in this or other variable. They are convenient intermediate values, not to repeat some simulations. The important part is the formula to define the domain - it takes the **relative** coordinates of the dipoles and performs some tests on it. If you write them explicitly, it is natural to define some combinations of constants as a separate one. `coat_r2` is exactly the example of such. And relative coordinates are taken relative to `sizeX`, which in this case is exactly the diameter (or twice the radius). 0.25=1/(2^2)

**Comment by hazraatrayee** [comment]
> > [1469](https://github.com/adda-team/adda/blob/master/src/make_particle.c) ` sh_form_str1="bisphere; diameter(d):";`
> > I have found that almost in every shape there is a diameter mention. Which diameter is it? because we are giving the values of ratio depending on the structures.
> 
> This diameter is given as the argument to the `-size` command line option or calculated from other input. Importantly, it is not an integral part of the shape (which is defined by dimensionless ratios). Any shape can then be scaled using `-size`. This explains the extra complications in specifying the description strings. See Section 6.2 "The computational grid" of the manual for more details.
> 
So it will take the diameter value given through `-size` automatically only by this `sh_form_str1="bisphere; diameter(d):";` comand?
After going through some portion of code what i have understood that this strings are stored in the log file. Is this data stored in log files will be used in simulation or stored for users?

**Comment by myurkin** [comment]
> So it will take the diameter value given through `-size` automatically only by this `sh_form_str1="bisphere; diameter(d):";` command?
> After going through some portion of code what i have understood that this strings are stored in the log file. Is this data stored in log files will be used in simulation or stored for users?

This strings are only stored in `log` for information purposes. The parameters that are used in simulations are taken directly from the command line or calculated from them. That's why I said from the beginning that understanding these strings is not critical.

> Another question related to this string, in case of `sh_form_str2` as example from bicoated:
> `sh_form_str2=dyn_sprintf(", center-center distance R_cc/d="GFORM", inner diameter d_in/d="GFORM, diskratio, coat_ratio);`
> here we are writing center to center distance or inner diameter and then taking the value of the ration given through `-shape` command line option. Why are we doing so?

Again, the values from the command line are actually further used in simulations. Here we just construct the information string, which is then saved to `log`. In other words, these string just repeats the description of this built-in shape from the manual, but inserts specific values specified in the command line.

**Comment by hazraatrayee** [comment]
As I was talking that I am right now trying to generate a shape that will be a some what like a coated one but there will another shell. that is two shell on a sphere. So now i need to specify 3 domains. Here we will have two coat ratios `coat_ratioI` and `cota_ratioII`.

coat_ratioI= dinter/dout 

Here I need a help, coat_ratioII will be din/dout?
I mean both the ratio must be taken with respect to the same d value? I am attaching the shape geometry here for your reference.

![bishell_structure (2)](https://user-images.githubusercontent.com/31928773/113234736-b0717380-9256-11eb-88f4-2fa4975b5870.jpg)

**Comment by myurkin** [comment]
There is no unique way to define those quantities. You define them in one place and then use in another one (to evaluate which domain a dipole belongs to). So the only requirement is that these two should be consistent with each other. The same applies to domains - it is your design choice.

Still, it seems that din/dout would be more convenient, and your choice of domains is the most logical (given other existing shapes in ADDA).

**Comment by hazraatrayee** [comment]
I am facing a problem. I have done this changes:
1. included the name in const.h
2. have introduced the geometry shape in param.c
3. have initialized and included details in make_particle.c

After doing this, i have complied param.c and make_particle.c
the result in terminal was exactly the same as that of before modification.

But the problem is that when I am checking by, ./adda -h shape, the new shape is not there.

I have tried for three times but the problem exists. 

Could you please help me in this matter?

**Comment by myurkin** [comment]
I am not completely sure, but you should:
1) compile not two files separately, but run whole compilation of ADDA (e.g. `make seq` in `src/`)
2) implement several changes in `param.c` - see https://github.com/adda-team/adda/wiki/AddingShape - check that you haven't missed anything.

**Comment by hazraatrayee** [comment]
As you suggested I have compiled in src by `make seq`. But the problem persists. The new shape is not present. In `adda -h shape` there is no change. And if I run program it is showing that there is no such shape name.


In the link i have gone through. I guess there is only one place where I need to incorporate and introduce the shap in param.c as I have mentioned the number of parameter in shape_opt. 

Is there any other thing need to be modified?

I am really confused. Please help me out

**Comment by myurkin** [comment]
1) Have you verified that the new executable is produced? Based on the #290, it may be that the compilation is not finished and you are running some old version of executable.
2) Search for `TO ADD NEW SHAPE` in `param.c` - there are several places that need to be modified.

**Comment by hazraatrayee** [comment]
![20210402_130812.jpg](https://user-images.githubusercontent.com/31928773/113393716-e93f4480-934b-11eb-86e2-e2504b1ebd1c.jpg)![20210402_130820.jpg](https://user-images.githubusercontent.com/31928773/113393728-ec3a3500-934b-11eb-94fd-e1b4adec71be.jpg)

I am getting this kind of error message

**Comment by hazraatrayee** [comment]
While complaining for the shape with previously compiled adda, i am getting error like:


![20210402_131032.jpg](https://user-images.githubusercontent.com/31928773/113393869-27d4ff00-934c-11eb-9e7a-0a01f9319816.jpg)

**Comment by hazraatrayee** [comment]
What I need to do now?

**Comment by myurkin** [comment]
I am not sure. You should take the code from github and compile it. Then modify (several files) and compile again. (better not to copy anything around).

But based on your output, you have problems with gfortran or you have modified (broken) the Makefile as well.

**Comment by hazraatrayee** [comment]
Thank you very much for you kind help and patience. Finally I am able to  compile ADDA and the problem was with gfotran in my ubuntu.
I have simulated one test run. but now the problem is though I have followed the structure generation of coated, the outer geometry is cubic instead of a sphere. The geometry that is generated is showing only two materials instead of three.

I think I need a little more time to generate the proper one.

I would like to request to keep this question open for a few more days.

**Comment by hazraatrayee** [comment]
I have simulated a sphere box structure and then studied the geometry file by LiteBil as found in FAQ.

The new multicoated sphere and sphere box geometry are showing the same the only difference when trying to look through individual material option is that there is 3 domains for this new structure. Although only two can be visualized.

Can you please help me in this visualization aspect. How to visualize every material or domain o any geometry created by simulation?

**Comment by myurkin** [comment]
In litebil you can look at cross sections (just try all the buttons in the upper row).

**Comment by hazraatrayee** [comment]
I have tried to get a visual 3Deffect of 3layered particle. But unfortunately still unable to get that. only 2 materials are shown at a time. I have no idea how to get all the layers at the same time.

But it is possible to get the cross-section in which all the layers are visible.

So for now I think my this problem is almost solved other than this 3D visualization. 

Thank you for your kind support Sir.

**Comment by myurkin** [comment]
That's good. So I close this issue. If you have any further questions, feel free to open a new one.
