### ISSUE TITLE
Running ADDA in OCL mode gives segfault errors

### ISSUE THREAD

**Issue by pulmonarycosignerkindness** [adda-team/adda#288]
### Describe the bug
When simulating a particle with adda_ocl I get a segmentation fault error after the simulation has converged (when it's done). This does not happen when running the same simulation with adda_mpi. However, OCL still outputs the mueller matrix and the CrossSec file, which have quite similar values compared to the MPI run. The log file often ends before it should, like for example,
```
ORIENTATION STEP beta=120 gamma=90

ORIENTATION STEP beta=120 gamma=270

ORIENTATION STEP beta=120 gamma=45

ORIENTATION STE
```
and then just nothing. Other runs it may be totally empty and not show anything at all. This only happens when running in OCL mode. 

I run ADDA from a bash file, which works for MPI mode, but for OCL I get the segfault error. The same error comes up even if i run the full command directly in the console.

### To reproduce
1. Prepare input files, such as parameters for orientation averaging (avg_params) and the shape file (adda.shape). 
2. Execute the bash file, which runs a command like `/.../adda/src/ocl/adda_ocl -shape read ./DIR/shape.adda -lambda 123456.78 -eq_rad 1234.123456789012 -dir ./DIR/ -eps 3 -orient avg ./DIR/avg_params -recalc_resid -m 1.7856473692013204 0.0001647288569182 9.2904691979307650 0.6877660225821125`
3. Examine the last lines in the console output;
```
Cabs    = 71020.09513
Qabs    = 0.0134221516
./execADDA_ocl.sh: line 23:  6580 Segfault  (memorydump created) /.../adda/src/ocl/adda_ocl -shape read ./DIR/shape.adda -lambda 123456.78 -eq_rad 1234.123456789012 -dir ./DIR/ -eps 3 -orient avg ./DIR/avg_params -recalc_resid -m 1.7856473692013204 0.0001647288569182 9.2904691979307650 0.6877660225821125
real    14m37,017s
user    4m44,477s
```
execADDA_ocl.sh is the bash file used to run ADDA. 

### Expected behavior
ADDA should finish the simulation without any errors, and write the full log to the log file. 

### Output
See above. I also have some error messages from the system logs:
```
ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj==unconfined pid=6580 comm="adda_ocl" exe="/.../adda/src/ocl/adda_ocl" sig=11 res=1

adda_ocl[6580]: segfault at 7fff63960ff8 ip 00007fbad2fa3d0a sp 00007fff63960fc0 error 6 in libc-2.33.so[7fbad2f42000+14c000]

Process 6580 (adda_ocl) of user 1000 dumped core.
Stack trace of thread 6580:
#0  0x00007fbad2fa3d0a n/a (n/a + 0x0)

```
There is a libc-2.33.so error, might be something?

### Technical information
- ADDA version: 1.4.0.  
- OS: Manjaro Linux KDE 5.20.5
- Compiler: GNU compilers version 10.2.0 (64-bit)
- GPU-accelerated version conforming to OpenCL standard 1.2
- Linked to clFFT version 2.12.2
- For OpenCL version, your GPU: AMD R9 390 8GB
- For MPI version, used MPI implementation: openmpi 4.0.5-2
- Versions of the libraries that may be related to the bug, such as FFTW3, clFFT, clBLAS: fftw 3.3.9-1, clfft 2.12.2-1, clblas 2.12-3

**Comment by myurkin** [comment]
Thanks for the report. I have tried to reproduce the issue with command line
`adda_ocl -shape sphere -lambda 123456.78 -eq_rad 1234.123456789012 -eps 3 -orient avg -recalc_resid -m 1.7856473692013204 0.0001647288569182 9.2904691979307650 0.6877660225821125`
but it works fine. So can you please either:
- provide all input files relevant to this run, so I can try to reproduce exactly your case, or
- (better) try to simplify the command line as much as possible keeping the segfault

Another question is whether the issue is always reproducible. I.e. if you repeat the command line several times, do you always get segfault?

And, as you mentioned, the issue maybe related to libc (and then I have no ideas what to do), but let's first investigate what we can on ADDA side.

**Comment by pulmonarycosignerkindness** [comment]
Hi, so I have run some more simulations, and the error seems to appear when I use a high (>2 ish) refractive index for the second material. 

The command you used works for me too (no errors), and so do some custom shapes & configurations I have tested. So OCL works, but not for all types of particles or properties. Some configurations always give an error even if I run them several times. 

For example, I now test with a particle with 2 materials and about 8000 grid points. If I use the real value for the refractive index for the second material, which is around 6, I get the segfault error. But if I set the refractive index for the second material to something lower, like 1, then it runs fine and finished without errors. 

For example, running this,
`adda_ocl -shape read ./shape.adda.melt.txt -lambda 19986.163866666666 -eq_rad 870.8471154266363 -eps 3 -orient avg ./avg_params.txt -recalc_resid -m 1.7856474059528551 0.0003979775880013 1.51728638 0.923867123`,
where I have a lower refractive index for the second material (~1.5 and ~1) works, but if I set the last two values to their real values; 6.0200693025972187 2.9411368112010470, where the command now is,
`adda_ocl -shape read ./shape.adda.melt.txt -lambda 19986.163866666666 -eq_rad 870.8471154266363 -eps 3 -orient avg ./avg_params.txt -recalc_resid -m 1.7856474059528551 0.0003979775880013 6.0200693025972187 2.9411368112010470`
then I get the segfault error. 

I'll attach the shape and avg_params file if you want to test it. 

-----
Some more journald errors that comes up after seeing the segfault error from ADDA in console;
```
Stack trace of thread 13321:
#0  0x00007fe9882a8d0a _int_free (libc.so.6 + 0x87d0a)
#1  0x00007fe9882acce8 __libc_free (libc.so.6 + 0x8bce8)
#2  0x00007fe987f3044a n/a (libMesaOpenCL.so.1 + 0x4744a)
#3  0x00007fe987f2a0b7 n/a (libMesaOpenCL.so.1 + 0x410b7)
#4  0x00007fe987f2a139 n/a (libMesaOpenCL.so.1 + 0x41139)
#5  0x00007fe987f29ea7 n/a (libMesaOpenCL.so.1 + 0x40ea7)
```

ADDA finished(?) the simulation, writes like this to console
```
...........
RE_018 = 8.1913766723E-04  + 
Final (recalculated) residual norm: 8.1913766723E-04

Error of alpha integration (Mueller) is 6.92397e-14
All inner integrations converged
The outer integration converged
In total 58 evaluations were used
Cext    = 131946.6372
Qext    = 0.05538148777
Cabs    = 122024.4597
Qabs    = 0.05121688785
```
and then it hangs for a few seconds, and then writes out `Segmentation fault (memory dump created)`. I get the CrossSec and mueller files, which look like they should, but the log file is cut in half like the example in my first message. 

Files: 
[avg_params.txt](https://github.com/adda-team/adda/files/6002953/avg_params.txt)
[shape.adda.melt.txt](https://github.com/adda-team/adda/files/6002960/shape.adda.melt.txt)

**Comment by myurkin** [comment]
I have tried your second command line
`adda_ocl -shape read ./shape.adda.melt.txt -lambda 19986.163866666666 -eq_rad 870.8471154266363 -eps 3 -orient avg ./avg_params.txt -recalc_resid -m 1.7856474059528551 0.0003979775880013 6.0200693025972187 2.9411368112010470` 
with the files that you provided on my Windows 10 notebook, using either Nvidia GTX 1050 or Intel HD 630 GPUs. The ADDA itself is 1.4.0 compiled with gcc 8.1.0 (the latter may be significant, since we already encountered some issues with gcc version 10). 

So I haven't encountered segfaults, however the simulation result is different, in particular
```
Cext	= 187681.607
Qext	= 0.07877492627
```

I am also attaching some of the output files from Nvidia run (with added `.txt` due to GitHub limitation). The ones from Intel HD are the same but slower.
[log_orient_avg.txt](https://github.com/adda-team/adda/files/6015183/log_orient_avg.txt)
[CrossSec.txt](https://github.com/adda-team/adda/files/6015184/CrossSec.txt)
[log.txt](https://github.com/adda-team/adda/files/6015185/log.txt)

Can you please double check that your result corresponds to the command line and input files that you provided? If yes, then please check that the `adda_mpi` run produces the same result. There is a minor possibility that `adda_ocl` produces incorrect output due to segfault (instead of complete failure).

**Comment by pulmonarycosignerkindness** [comment]
I checked my files again, and the log output I wrote in my second message is for the first command (with a different refraction index for the second material). The second command (the same you wrote) gives me identical results as you got,
```
Cext	= 187681.607
Qext	= 0.07877492627
```
And this is still giving me a segfault error, and a half-written log file. Running the same command with `adda_mpi` instead gives me the same output as when using `adda_ocl`, but without the segfault error. So `adda_ocl` seems to work, except for the log file which is always half-missing. 

Log file for ocl run: [log.txt](https://github.com/adda-team/adda/files/6020582/log.txt)

**Comment by myurkin** [comment]
So it seems that segfault happens when writing to `log`, when its size is close to 4096 (seems to be a standard system buffer). ADDA just calls `fprintf` for that, which should never lead to segfault. So, it seems to be a strange problem with system libraries exclusively in OCL mode, the latter I cannot understand.

Can you please test the following command line?
`adda_ocl -grid 16 -m 0 5 -size 1`
It should lead to a long log file due to a lot of iterations of the iterative solver - let's see if this will cause segfault as well.

**Comment by pulmonarycosignerkindness** [comment]
`adda_ocl -grid 16 -m 0 5 -size 1`, works just fine with `adda_ocl`. No segfaults, and a full log file generated. 
[log.txt](https://github.com/adda-team/adda/files/6021569/log.txt)

**Comment by myurkin** [comment]
Thanks for the detailed tests. Now it seems that segfault happens after all calculations are complete, but part of the `log` is not yet flushed. To test this, can you please additionally test ADDA in debug mode. For that compile it using:
`make ocl OPTIONS=DEBUGFULL`
And then run any simulation that produced segfault before. If you get the segfault, please share the output.

**Comment by pulmonarycosignerkindness** [comment]
Compiled ADDA ocl like you said and ran the same command as above; `adda_ocl -grid 24 -m 0 5 -size 1`. Got the segfault error again, but not sure if the debug says anything helpful. I pasted some of the console output at the bottom again. 

Log: [log.txt](https://github.com/adda-team/adda/files/6023027/log.txt)

**Comment by myurkin** [comment]
Actually the debug is useful - it suggests that segfault happens in `oclunload()` in oclcore.c . I have added some debugging information there. Can you please:
* pull the recent source
* uncomment two lines starting from
  https://github.com/adda-team/adda/blob/741217c5b21772b727104d572067106141a82a70/src/oclcore.c#L529
* compile `adda_ocl` in debug mode
* run some command line leading to segfault
* share the output (`stdout`) here (at least several last lines)

**Comment by pulmonarycosignerkindness** [comment]
Did as you said, here's the log: [log.txt](https://github.com/adda-team/adda/files/6027392/log.txt),
and here are the last lines from console;
```
DEBUG: ../calculator.c:655: MuellerMatrix finished 
DEBUG: ../oclcore.c:533: oclunload started 
Executing 'clReleaseProgram(program)'
Executing 'clReleaseKernel(clzero)'
Executing 'clReleaseKernel(clarith1)'
Executing 'clReleaseKernel(clarith2)'
Executing 'clReleaseKernel(clarith3)'
Executing 'clReleaseKernel(clarith4)'
Executing 'clReleaseKernel(clarith5)'
Executing 'clReleaseKernel(clnConj)'
Executing 'clReleaseKernel(clinprod)'
Executing 'clReleaseKernel(cltransposeof)'
Executing 'clReleaseKernel(cltransposeob)'
Executing 'clReleaseCommandQueue(command_queue)'
Segmenteringsfel (minnesutskrift skapad)
```

**Comment by myurkin** [comment]
I probably have a fix for that. Can you please test the latest source?

**Comment by pulmonarycosignerkindness** [comment]
Tested it, but unfortunately it still gives me a segfault error. I also recompiled it twice, but nope. 
[log.txt](https://github.com/adda-team/adda/files/6034221/log.txt)
`/adda/src/ocl/adda_ocl -grid 24 -m 0 5 -size 25`

```
RE_37183 = 1.0003631399E-05  + 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.00062 
RE_37184 = 1.0002553111E-05  + 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.0016 
RE_37185 = 1.0002563451E-05  - 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.0031 
RE_37186 = 1.0000399484E-05  + 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.0013 
RE_37187 = 9.9974559982E-06  + 
DEBUG: ../CalculateE.c:857: Iterative solver finished 
DEBUG: ../CalculateE.c:493: Accumulating Eplane started 
DEBUG: ../CalculateE.c:496: Accumulating Eplane finished 
DEBUG: ../CalculateE.c:493: Accumulating Eplane started 
DEBUG: ../CalculateE.c:496: Accumulating Eplane finished 
DEBUG: ../CalculateE.c:716: Calculation of cross sections started 
DEBUG: ../CalculateE.c:732: Cext and Cabs calculated 
Cext    = 1184.619999
Qext    = 2.413288045
Cabs    = 0
Qabs    = 0
DEBUG: ../CalculateE.c:823: Calculation of cross sections finished 
DEBUG: ../calculator.c:653: CalculateE finished 
DEBUG: ../calculator.c:655: MuellerMatrix finished 
Segmenteringsfel (minnesutskrift skapad)
```

**Comment by myurkin** [comment]
Yes, that's a pity. Then please uncomment the two lines, we discussed previously. And if the segfault happens after
`Executing 'clReleaseCommandQueue(command_queue)'`
as previously, then please insert the following line 
`CL_CH_ERR(clFinish(command_queue));` 
before
https://github.com/adda-team/adda/blob/edf359dbd2894703d227c6b0c7998dea06cde7ef/src/oclcore.c#L549
and recompile/run.

**Comment by pulmonarycosignerkindness** [comment]
No, that didn't work either :/

**Comment by myurkin** [comment]
Can you please paste the last lines of stdout from the latter run. Does it include `Executing 'clFinish...`?

**Comment by pulmonarycosignerkindness** [comment]
```
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.00045 
RE_37182 = 1.0004372234E-05  + 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.0088 
RE_37183 = 1.0003631399E-05  + 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.00062 
RE_37184 = 1.0002553111E-05  + 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.0016 
RE_37185 = 1.0002563451E-05  - 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.0031 
RE_37186 = 1.0000399484E-05  + 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.0013 
RE_37187 = 9.9974559982E-06  + 
DEBUG: ../CalculateE.c:857: Iterative solver finished 
DEBUG: ../CalculateE.c:493: Accumulating Eplane started 
DEBUG: ../CalculateE.c:496: Accumulating Eplane finished 
DEBUG: ../CalculateE.c:493: Accumulating Eplane started 
DEBUG: ../CalculateE.c:496: Accumulating Eplane finished 
DEBUG: ../CalculateE.c:716: Calculation of cross sections started 
DEBUG: ../CalculateE.c:732: Cext and Cabs calculated 
Cext    = 1184.619999
Qext    = 2.413288045
Cabs    = 0
Qabs    = 0
DEBUG: ../CalculateE.c:823: Calculation of cross sections finished 
DEBUG: ../calculator.c:653: CalculateE finished 
DEBUG: ../calculator.c:655: MuellerMatrix finished 
Segmenteringsfel (minnesutskrift skapad)
```
Doesn't seem like it. It's similar to the one above

**Comment by myurkin** [comment]
Please uncomment two lines starting from:
https://github.com/adda-team/adda/blob/edf359dbd2894703d227c6b0c7998dea06cde7ef/src/oclcore.c#L529
It will produce more debugging info from function `oclunload`. And then paste here the output again.

**Comment by pulmonarycosignerkindness** [comment]
They are uncommented;
```
#ifdef DEBUGFULL
	// uncomment the following two lines to further debug clRelease... calls
	#undef CL_CH_ERR
	#define CL_CH_ERR(a) printf("Executing '"#a"'\n");fflush(stdout);CheckCLErr(a,ALL_POS,NULL)
#endif
```
Unless I should remove the `#` too, but that just gives me compilation errors if I remove them.

**Comment by myurkin** [comment]
That's strange. I thought you should have the output similar to the one in https://github.com/adda-team/adda/issues/288#issuecomment-783983487

Well, unless now the segfault happens at `clFinish` before `clunload` is reached... Let me think further about it.

**Comment by myurkin** [comment]
Can you please try to produce the backtrace, like you did before - https://github.com/adda-team/adda/issues/288#issuecomment-781332293, but now with ADDA compiled in debug mode - it may contain more information.

**Comment by myurkin** [comment]
Also, I've noticed that you're using MESA OpenCL implementation. Here are few ideas with varying complexity:
* Show here the installed version of MESA
* If it's not the latest one, upgrade to the latest one
* Try AMD OpenCL implementation (can be more stable with AMD cards). Coming back to your suggestion above, the old GPU is not a problem per se, rather it can be incompatible with some old (or even recent) drivers (especially, when the latter are created by a different vendor).

**Comment by myurkin** [comment]
Apart from that, my conclusion from googling this problem is that it may potentially be the issue with some opencl kernels in ADDA, which  show themselves only when clFinish is called (and only on this hardware and these specific runs). However, that does not helps us much, since debugging OpenCL code is hard (requires some SDK to do it conveniently) and need to be done on your system.

One another simple thing to try is to comment out the line:
https://github.com/adda-team/adda/blob/edf359dbd2894703d227c6b0c7998dea06cde7ef/src/calculator.c#L1023
i.e. to turn off all cleaning up at the end of ADDA run. 

If that helps (removes segfault), we can try a more localized intervention **instead**: comment out the following lines:
https://github.com/adda-team/adda/blob/edf359dbd2894703d227c6b0c7998dea06cde7ef/src/fft.c#L1469
and two lines starting from
https://github.com/adda-team/adda/blob/edf359dbd2894703d227c6b0c7998dea06cde7ef/src/oclcore.c#L549

**Comment by pulmonarycosignerkindness** [comment]
It worked! :D I removed opencl-mesa and installed opencl-amd instead, and now i didn't get a segfault. Good suggestion to try AMD's version instead. 

The log file is now complete (not cut off), and I also have the CrossSec and mueller files. 

Console output: 
```
RE_36146 = 1.0015362106E-05  - 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.0036 
RE_36147 = 1.0008422428E-05  -+
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.0092 
RE_36148 = 9.9735388019E-06  + 
DEBUG: ../CalculateE.c:857: Iterative solver finished 
DEBUG: ../CalculateE.c:493: Accumulating Eplane started 
DEBUG: ../CalculateE.c:496: Accumulating Eplane finished 
DEBUG: ../CalculateE.c:493: Accumulating Eplane started 
DEBUG: ../CalculateE.c:496: Accumulating Eplane finished 
DEBUG: ../CalculateE.c:716: Calculation of cross sections started 
DEBUG: ../CalculateE.c:732: Cext and Cabs calculated 
Cext    = 1184.624818
Qext    = 2.413297862
Cabs    = 0
Qabs    = 0
DEBUG: ../CalculateE.c:823: Calculation of cross sections finished 
DEBUG: ../calculator.c:653: CalculateE finished 
DEBUG: ../calculator.c:655: MuellerMatrix finished 
DEBUG: ../oclcore.c:533: oclunload started 
Executing 'clReleaseProgram(program)'
Executing 'clReleaseKernel(clzero)'
Executing 'clReleaseKernel(clarith1)'
Executing 'clReleaseKernel(clarith2)'
Executing 'clReleaseKernel(clarith3)'
Executing 'clReleaseKernel(clarith4)'
Executing 'clReleaseKernel(clarith5)'
Executing 'clReleaseKernel(clnConj)'
Executing 'clReleaseKernel(clinprod)'
Executing 'clReleaseKernel(cltransposeof)'
Executing 'clReleaseKernel(cltransposeob)'
Executing 'clReleaseCommandQueue(command_queue)'
Executing 'clReleaseContext(context)'
DEBUG: ../oclcore.c:551: oclunload finished 
DEBUG: ../ADDAmain.c:98: Calculator finished
```
-----------
Here's the comment I was about to post before I installed AMD OpenCL instead;

mesa version: 20.3.4-1, which is the latest available one for me. 

Backtrace = The system logs?
I ran `adda/src/ocl/adda_ocl -grid 24 -m 0 5 -size 25` again, and got the same console output;
```
RE_37186 = 1.0000399484E-05  + 
DEBUG: ../iterative.c:1038: |vT.v|/(v.v)=0.0013 
RE_37187 = 9.9974559982E-06  + 
DEBUG: ../CalculateE.c:857: Iterative solver finished 
DEBUG: ../CalculateE.c:493: Accumulating Eplane started 
DEBUG: ../CalculateE.c:496: Accumulating Eplane finished 
DEBUG: ../CalculateE.c:493: Accumulating Eplane started 
DEBUG: ../CalculateE.c:496: Accumulating Eplane finished 
DEBUG: ../CalculateE.c:716: Calculation of cross sections started 
DEBUG: ../CalculateE.c:732: Cext and Cabs calculated 
Cext    = 1184.619999
Qext    = 2.413288045
Cabs    = 0
Qabs    = 0
DEBUG: ../CalculateE.c:823: Calculation of cross sections finished 
DEBUG: ../calculator.c:653: CalculateE finished 
DEBUG: ../calculator.c:655: MuellerMatrix finished 
Segmenteringsfel (minnesutskrift skapad)
```
with these lines in the system logs;
```
ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=2 subj==unconfined pid=33323 comm="adda_ocl" exe="/adda/src/ocl/adda_ocl" sig=11 res=1
```
```
adda_ocl[33323]: segfault at 7ffbffa93ff8 ip 00007f54fd44c39f sp 00007ffbffa93fd0 error 6 in libMesaOpenCL.so.1.0.0[7f54fd421000+7b000]
```
```
Code: ff 66 2e 0f 1f 84 00 00 00 00 00 41 56 4c 8d 35 d7 c7 ff ff 41 55 41 54 55 48 89 fd 53 48 83 ec 30 64 48 8b 04 25 28 00 00 00 <48> 89 44 24 28 48 8b 07 48 8b 40 18 4c 39 f0 0f 85 ac 00 00 00 48
```
```
audit: type=1701 audit(1614166404.996:240): auid=1000 uid=1000 gid=1000 ses=2 subj==unconfined pid=33323 comm="adda_ocl" exe="/adda/src/ocl/adda_ocl" sig=11 res=1
```
```
Process 33323 (adda_ocl) of user 1000 dumped core.

Stack trace of thread 33323:
#0  0x00007f54fd44c39f n/a (libMesaOpenCL.so.1 + 0x4039f)
#1  0x00007f54fd44c3dd n/a (libMesaOpenCL.so.1 + 0x403dd)
#2  0x00007f54fd44c3dd n/a (libMesaOpenCL.so.1 + 0x403dd)
...
```
which is really long, and further down it says,
```
...
Stack trace of thread 33325:
#0  0x00007f54fd57b9ba __futex_abstimed_wait_common64 (libpthread.so.0 + 0x159ba)
#1  0x00007f54fd575260 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf260)
#2  0x00007f54f207b5dc n/a (pipe_radeonsi.so + 0xf35dc)
#3  0x00007f54f207b048 n/a (pipe_radeonsi.so + 0xf3048)
#4  0x00007f54fd56f299 start_thread (libpthread.so.0 + 0x9299)
#5  0x00007f54fd886153 __clone (libc.so.6 + 0xff153)
```
over and over.  

--------------
So it was probably something not working with my GPU and the MESA OpenCL implementation. I'm now on opencl-amd 20.45.1165792-4. 

Tell me if I should switch back to opencl-mesa and try the last thing you wrote. https://github.com/adda-team/adda/issues/288#issuecomment-785021284

**Comment by myurkin** [comment]
Great! I think we can consider this issue solved. Indeed, it seems that there is some inconsistency in MESA OpenCL for your specific GPU. And thanks for your patience in testing many different ideas. Together, we improved the source of ADDA a little bit, although that didn't help with this issue.

Concerning further tests. In principle, it makes sense to file a bug report to MESA, but it will probably be hard for them to investigate it, since it shows itself only in a long ADDA run (it would be much easier, if the bug is localized to some simple OpenCL code, but our tests above do not suggest such easy possibility). So it's up to you to decide if you want to pursue this line of action.
