### ISSUE TITLE
problem with code download

### ISSUE THREAD

**Issue by hazraatrayee** [adda-team/adda#290]
I was trying to download the ADDA code for a few hours and found that each and every time in seq folder there is only make file. what should i do now?

**Comment by myurkin** [comment]
Well, this is as it should be. The executable will appear in this folder only after compilation (to be executed in folder `src/`. The precompiled executables are available only for Windows and in a separate downloadable package.

**Comment by hazraatrayee** [comment]
But when I am executing `make seq` in src, the main adda.c remains missing.

In the terminal it is showing that, ![20210402_123301.jpg](https://user-images.githubusercontent.com/31928773/113390550-d118f680-9346-11eb-8dae-47cb99ce4173.jpg)

But previously I have not faced such problem. What to do now?

**Comment by myurkin** [comment]
It seems that you are missing `gfortran`. There should be some message about it in the beginning of compilation.
