### ISSUE TITLE
Problem with CrossSec-Y file generation

### ISSUE THREAD

**Issue by hazraatrayee** [adda-team/adda#297]
### First, search in other sources of information:
* Home wiki page (getting started) - https://github.com/adda-team/adda/wiki
* FAQ - https://github.com/adda-team/adda/wiki/FAQ
* manual - https://github.com/adda-team/adda/blob/master/doc/manual.pdf

### Second, search through existing questions:
* in the discussion group - https://groups.google.com/forum/#!forum/adda-discuss
* in the issue tracker - https://github.com/adda-team/adda/issues?q=label:question+

### Third, consider addressing sending the question to the discussion group:
Many ADDA users are subscribed, so you may get more specific and faster answer. And those answers are more convenient to search through.
* by e-mail: mailto:adda-discuss@googlegroups.com
* through the web interface: https://groups.google.com/forum/#!newtopic/adda-discuss

**Comment by hazraatrayee** [comment]
Dear Maxium, probably you remember that I was trying to generate a new structure similar to core-shell. I am now trying to generate spectrum for that structure. Now there is a problem. 
I am giving the wavelength and refractive indices from a shell script to generate the spectrum automatically. In that shell script output it was showing that core dumped and segmentation error. then I have found that for some particular wavelengths the crossSec-Y file is not generated. As  I checked the log file i found that the problem is with iteration number. 

The last message written on the log file is,: Error: (../iterative.c:1525) Residual norm haven't decreased for maximum allowed number of iteration (50000). 

What now I should do?

**Comment by hazraatrayee** [comment]
Earlier I was doing the simulation for grid 32.

to test now I am running the program with grid 16. The points where there was problem with iteration, now the Crosssec-Y file is been generated for those points.

But what if i need to give a higher grid value for accuracy of my final spectrm?

How to solve this problem? please help.

**Comment by myurkin** [comment]
Dear Atrayee, I have added the answer to this question to FAQ - see https://github.com/adda-team/adda/wiki/FAQ#iterative-solver-breaks-down

I may provide more specific advice, if you provide more details about the specific ADDA run that breaks down. For example, upload the log file here.
