### ISSUE TITLE
install MPI

### ISSUE THREAD

**Issue by zhuimsda-daad** [adda-team/adda#323]
After installing MPI, I run the command 'time mpiexec - N 24. / ADDA master / SRC / MPI / ADDA_ mpi -shape sphere -size 5.2 -dpl 15 -m 1.2 0.0010 -lambda 0.3988 -scat_ grid_ inp ./scat_ params. dat -store_ scat_ grid'The following error will appear in grid ':

./adda-masterc/mpi/adda_ mpi:error while loading shared libraries :libmpi.so. 20:cannot open shared objiec file:No such file or directory

Did I install the software incorrectly?

**Comment by myurkin** [comment]
Again, based on the limited information, it is hard to provide a specific advice. It seems that there are problems with configuration of the MPI on your system. For instance, it may be installed, but you may need to initialize some environmental variables in your profile file. Usually, this is done automatically by the package manager. 

I recommend to read the docs for the MPI implementation that you use and try to run examples that are provided with it.

**Comment by myurkin** [comment]
Do you have any more questions concerning this issue? If not, I will close it.

**Comment by zhuimsda-daad** [comment]
no,very thanks for you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Maxim ***@***.***&gt;; 
发送时间: 2022年9月30日(星期五) 晚上8:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [adda-team/adda] install MPI (Issue #323)





 
Do you have any more questions concerning this issue? If not, I will close it.
