### ISSUE TITLE
Simulation of Light Scattering of Core Shell Particle within absorption medium

### ISSUE THREAD

**Issue by JohnLee009** [adda-team/adda#330]
Hi,

is the current code able to simulate the light scattering of core shell particle within absorption medium?

The core shell particle could be the shell is polymer and the core is just air. And the medium is another kind of polymer.

Many thanks for your help!

Best,

John

**Comment by myurkin** [comment]
John, thanks for your interest. The master branch doesn't support it. However, see the comments inside issues #91 and #219. Briefly, there is a beta-version in https://github.com/Sunmosk/adda-complex_freq , developed by Alexander Moskalensky (@Sunmosk), which was later incorporated (together with the EELS functionality) into the pull request #314. However, the latter has not yet been merged into the master branch (my fault, I hope to do it within a few months). So, you can already run some simulations with it, but there is almost no documentation.

Another (more global) issue is how the measureable quantities, like extinction cross section, should be calculated in such case. The current code implement one of the options, but it is not the only possibility. We discussed these issues in a couple of conference presentations. However, we haven't yet finalized the comprehensive journal papers on this subject (again, my fault). 
1. Moskalensky A.E. and Yurkin M.A. Open-source implementation of the DDA for light scattering in an absorbing medium, _The 19th Electromagnetic and Light Scattering Conference_, 12 July 2021, Online, _Book of Abstracts of the 19th Conference on Electromagnetic & Light Scattering_, [p. 48](https://els2021.physics.itmo.ru/files/ELS%202021.%20Book%20of%20abstracts.pdf). ([poster](https://www.researchgate.net/publication/354652891_Poster_METANANO-2021_absorbing)) 
1. Yurkin M.A. and Moskalensky A.E. Open-source implementation of the discrete-dipole approximation for a scatterer in an absorbing host medium, _VI International Conference on Metamaterials and Nanophotonics (METANANO 2021)_, 13 September 2021, Online, _J. Phys.: Conf. Ser._ **2015**, [p. 012167](http://doi.org/10.1088/1742-6596/2015/1/012167). ([video](https://youtu.be/oTNgwosc-s0))

To conclude, if you decide to give it a try, we will be glad to answer any questions. And please provide feedback, how it works for you.

**Comment by JohnLee009** [comment]
Hi Maxim, many thanks for your detailed answer. I will try to run the simulations. Once I get some results, will definitely update with the community.
