### ISSUE TITLE
Field distribution

### ISSUE THREAD

**Issue by hazraatrayee** [adda-team/adda#334]
I want a field distribution diagram. I have created wrapped version for generating spectrum using code giving the option to select size and refractive index files. Now i want to get the field distribution of the particle. Can you please help guiding me about how can I get the distribution?

**Comment by myurkin** [comment]
Dear Atrayee, if you want internal fields, you can get them by `-store_int_field`. See Section 11.7 "Internal fields and dipole polarizations" of the manual.

For near-fields, you may use one of the options described at:
https://github.com/adda-team/adda/wiki/FAQ#how-to-calculate-near-field-using-adda
