### ISSUE TITLE
New particle shapes

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adda-team/adda#34]
```
Implement general shapes like 'coated ellipsoid', 'boxsphere', 'spherebox'
with a lot of input parameters. It may be also implemented as a arbitrary
composition of basic shapes.

```

Original issue reported on code.google.com by `yurkin` on 24 Dec 2008 at 7:04

**Comment by myurkin** [comment]
Another idea is to use this tool - https://github.com/karimnaaji/voxelizer

**Comment by myurkin** [comment]
Super-ellipsoid is another idea - very broad class and should be easy to implement. See https://en.wikipedia.org/wiki/Superellipsoid

**Comment by myurkin** [comment]
I have moved several ideas for new shapes to separate issues (in addition to those mentioned above) - #292, #293, #294, #295 . So the issue can now be closed.
