### ISSUE TITLE
Second Order formulation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adda-team/adda#37]
```
Further develop SO formulation, bring it out of the development phase.

```

Original issue reported on code.google.com by `yurkin` on 24 Dec 2008 at 7:13

**Comment by myurkin** [comment]
We decided to stop this development, as most of the benefits is expected to be present in the new analytical igt_so formulation (#299), which will have accompanying paper describing all formulae (which are fully self-consistent). The corresponding SO code will be removed to improve maintainability, but can always be found in git. The simplest part of SO formulation is `-scat so` which may potentially be used in #220. The potential benefit of other legacy code is very unclear.
