### ISSUE TITLE
Use need-lock on binary files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [adda-team/adda#69]
```
We tried it already
http://code.google.com/p/a-dda/source/detail?r=826
but Google do not yet support svn locks, although the issue is open
http://code.google.com/p/support/issues/detail?id=1349

If it will ever be implemented, then we will return to this issue.
```

Original issue reported on code.google.com by `yurkin` on 8 Apr 2009 at 6:45

**Comment by myurkin** [comment]
That seems to be possible on GitHub - https://github.com/git-lfs/git-lfs/wiki/File-Locking
But we do not need it for all binary files, rather for those that are editable (and not mergeable). For now, that seems to be limited to .docx .
By contrast, images, pdfs, exe, dll are mostly replaced by a new version, which is created from some sources. For them no merge conflicts are expected.
